In [21]:
import numpy as np

In [22]:
n1=np.array([1,2,3,4])

In [23]:
n1

array([1, 2, 3, 4])

In [33]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [25]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
#1 Init with zero, Ones, x number and random number

In [27]:
n3=np.zeros((5,5))

In [28]:
n3


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
n4=np.ones((5,5))

In [30]:
n4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
n5=np.full((5,5),10)

In [32]:
n5

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [38]:
n6=np.random.randint(1,100,5)

In [39]:
n6

array([50, 23, 58, 44, 83])

In [40]:
#2 Checking the shape and change it

In [48]:
n7 = np.array([[1,2,3,4],[2,4,5,7]])

In [53]:
n7.shape

(2, 4)

In [54]:
n7.shape=(4,2)

In [55]:
n7

array([[1, 2],
       [3, 4],
       [2, 4],
       [5, 7]])

In [56]:
#3 Joining numpy Arrays

In [58]:
n8=np.array([3,4,5,6])
n9=np.array([4,3,5,7])

In [67]:
# vStack

np.stack((n8,n9))

array([[3, 4, 5, 6],
       [4, 3, 5, 7]])

In [65]:
# hStack

np.hstack((n8,n9))

array([3, 4, 5, 6, 4, 3, 5, 7])

In [68]:
# column-stack

np.column_stack((n8,n9))

array([[3, 4],
       [4, 3],
       [5, 5],
       [6, 7]])

In [69]:
#4 Numpy Intersection and Difference

In [70]:
#Intersection
np.intersect1d(n8,n9)

array([3, 4, 5])

In [72]:
#Diff n1
np.setdiff1d(n8,n9)

array([6])

In [75]:
#Diff n2
np.setdiff1d(n9,n8)

array([7])

In [79]:
#5 Array sum

In [78]:
np.sum((n8,n8))

36

In [77]:
np.sum((n8,n9),axis=0)

array([ 7,  7, 10, 13])

In [80]:
np.sum((n8,n8),axis=1)

array([18, 18])

In [81]:
# 6 Numpy Mathematics Operations

In [92]:
n9 = np.array([4,5,6,7])
n9 = n9 + 1

In [93]:
n9


array([5, 6, 7, 8])

In [94]:
n9 = n9 * 3
n9

array([15, 18, 21, 24])

In [95]:
n9 = n9 - 2
n9

array([13, 16, 19, 22])

In [97]:
n9 = n9 / 4
n9

array([0.8125, 1.    , 1.1875, 1.375 ])

In [98]:
#9 Numpy Stats


In [99]:
np.mean(n9)

1.09375

In [101]:
np.median(n9)

1.09375

In [103]:
np.std(n9)

0.2096313728906053

In [104]:
np.var(n9)

0.0439453125

In [105]:
# Save and load

In [112]:
np.save('numpy',n9)

In [116]:
n10=np.load('numpy.npy')

In [117]:
n10

array([0.8125, 1.    , 1.1875, 1.375 ])